dealsList = [
    {"date": "1.26.25",
      "intro": "A Good Deal on a Very Thin Memory Foam Pillow:",
      "title": "Blissbury Stomach Sleeping Pillow - Thin Memory Foam",
      "normalprice": "$47.99",
      "dealprice": "$44.99",
      "description": "There is a lot of competition in this part of the market. If you know the exact hight you want to the tenth of an inch, you can probably find it. But if you're not sure yet, Blissbury is starting to make a name for itself as a good option. This pillow is 3.3 inches thick, but you can also get an even thinner version that it only is 2.6 inches.",
      "see": "/thin",
      "link": "https://amzn.to/3OlAxjn"},
    {"date": "1.22.25",
      "intro": "A Great Deal on a Memory Foam Pillow that is Adjustable in Height:",
      "title": "USlixury Adjustable Side Sleeper Pillow",
      "normalprice": "$40.99",
      "dealprice": "$33.99",
      "description": "Despite the less than admirable spelling of its name, this pillow is a good option for people who need a thin pillow. <br><br> It is adjustable in height, so you can make it as thin as you need. It is also a great option for side sleepers because of the presence of a cutout that allows your shoulders to align with your head while you sleep on your side.",
      "see": "/memory-foam",
      "link": "https://amzn.to/40NtpU8"},
    { "date": "1.20.25",
      "intro": "An Even Better Deal On a High Quality Cooling Pillow",
      "title": "Tempur-Pedic TEMPUR-Cloud Dual Cooling Pillow - Queen",
      "normalprice": "$189.00",
      "dealprice": "$82.99",
      "description": "Not everyone likes the springiness of latex. If you're one of those people, you might have to go with a more traditional opition. Tempur-pedic has been making good, but expensive pillows for ages. Somehow, their memory foam manages to be more supportive than everyone else's. Tempur-Pedic is actually one of the few brands than has figured out how to make a cooling pillow cover that works more often than not.  <br><br> But, in many cases, it's still just a cover over a hot pillow. This pillow is a bit different. It has an internal gel layer meant to prevent the heat from building up to begin with.",
      "see": "/cooling",
      "link": "https://amzn.to/3YUEhNo"},
    { "date": "1.15.25",
      "intro": "A Good Deal On an Adjustable Shredded Memory Foam Pillow",
      "title": "Coop Home Goods Original Adjustable Pillow - Queen",
      "normalprice": "$79,00",
      "dealprice": "$63.20",
      "description": "Memory foam isn't for everyone, but if you like it and don't sleep hot, this is one of the best adjustable height pillows out there.",
      "see": "/shredded-foam",
      "link": "https://amzn.to/4eATmti"},
    { "date": "1.8.25",
      "intro": "A Good Deal On a High Quality Cooling Pillow",
      "title": "Tempur-Pedic TEMPUR-Cloud Dual Cooling Pillow - Queen",
      "normalprice": "$189.00",
      "dealprice": "$155.22",
      "description": "Not everyone likes the springiness of latex. If you're one of those people, you might have to go with a more traditional opition. Tempur-pedic has been making good, but expensive pillows for ages. Somehow, their memory foam manages to be more supportive than everyone else's. Tempur-Pedic is actually one of the few brands than has figured out how to make a cooling pillow cover that works more often than not.  <br><br> But, in many cases, it's still just a cover over a hot pillow. This pillow is a bit different. It has an internal gel layer meant to prevent the heat from building up to begin with.",
      "see": "/cooling",
      "link": "https://amzn.to/3YUEhNo"},
    { "date": "1.7.25",
      "intro": "A Good Deal On an Affordable (and Fluffy) Set of Down Alternative Pillows",
      "title": "Bedsure Down Alternative Pillows (set of 2)",
      "normalprice": "$25.00",
      "dealprice": "$19.79",
      "description": "The Bedsure Pillows (queen) (which come in sets of 2) are down alternative pillows with a polyester fill that are approximately 9 1/2 inches thick (so definitely on the fluffy side).  They are incredibly popular, having an average rating of 4.3 stars with over 14,000 reviews.",
      "see": "/most-popular",
      "link": "https://amzn.to/482LPC7"},
    {"date": "1.3.25",
      "intro": "A Good Deal on a Memory Foam Pillow that is Adjustable in Height:",
      "title": "USlixury Adjustable Side Sleeper Pillow",
      "normalprice": "$40.99",
      "dealprice": "$36.89",
      "description": "Despite the less than admirable spelling of its name, this pillow is a good option for people who need a thin pillow. <br><br> It is adjustable in height, so you can make it as thin as you need. It is also a great option for side sleepers because of the presence of a cutout that allows your shoulders to align with your head while you sleep on your side.",
      "see": "/memory-foam",
      "link": "https://amzn.to/40NtpU8"},
]

